# Generated by Django 4.2 on 2023-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('demo', models.FileField(upload_to='portfolio/media/demos')),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True)),
                ('created_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/media/thumbnails')),
            ],
        ),
    ]
