# Generated by Django 4.2 on 2023-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_demo_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order_number']},
        ),
        migrations.AddField(
            model_name='project',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
